# Generated by Django 2.1.2 on 2018-10-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.Category'),
            preserve_default=False,
        ),
    ]
